# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

# output "kubectl_config" {
#   description = "kubectl config as generated by the module."
#   value       = data.terraform_remote_state.eks.outputs.kubectl_config
#   sensitive   = true
# }

