name: "Openfaas with kind and terraform"

on:
  push:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.2.0
        with:
          cluster_name: openfaas

      - name: Checkout
        uses: actions/checkout@v2

      - name: Checkout submodules
        run: git submodule update --init --recursive

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color
        continue-on-error: true

      - name: Terraform Plan Status
        if: steps.plan.outcome == 'failure'
        run: exit 1

      - name: Terraform Apply
        run: terraform apply -auto-approve

      - name: kubectl status
        run: |
          kubectl config set-context kind-openfaas --namespace openfaas
          #kubectl describe crds/functions.openfaas.com
          kubectl get deployments

          kubectl get functions
          kubectl get svc gateway-external -o wide

          kubectl -n openfaas-fn wait --for=condition=Ready pods --timeout=300s --all
          kubectl -n openfaas-fn get pods

      - name: Test service URLs
        run: |
          ./test/test.sh
